sudo: false

language: node_js

node_js:
  - "6.11.1"

services:
  - docker

git:
  depth: 200

before_install:
# checkout master branch for all submodules
- git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; [ -z "$branch" ] && git checkout master || git checkout $branch'

# Changes in config.js for docker containers to run properly
- sed -i -e 's/- \/src\/Hilary/- \/home\/travis\/build\/brecke\/Hilary/g' docker-compose.yml
- sed -i -e 's/- \/src\/files/- \/home\/travis\/build\/brecke\/files/g' docker-compose.yml
- sed -i -e 's/\/src\/tmp/\/home\/travis\/build\/brecke\/tmp/g' docker-compose.yml
# config.ui path
- printf "\n\nconfig.ui.path = './3akai-ux';" >> config.js
# cassandra
- printf "\n\nconfig.cassandra.hosts = ['oae-cassandra'];" >> config.js
# redis
- printf "\n\nconfig.redis.host = 'oae-redis';" >> config.js
# elasticsearch
- printf "\n\nconfig.search.hosts[0].host = 'oae-elasticsearch';" >> config.js
# rabbitmq
- printf "\n\nconfig.mq.connection.host = 'oae-rabbitmq';" >> config.js
# etherpad
- printf "\n\nconfig.etherpad.hosts[0].host = 'oae-etherpad';" >> config.js
# previews
- printf "\n\nconfig.previews.enabled = true;" >> config.js
# e-mail
- printf "\n\nconfig.email.debug = false;" >> config.js
- printf "\n\nconfig.email.transport = 'sendmail';" >> config.js

install:
# build the hilary:latest image
- docker-compose create --build
# install dependencies for oae-rest
- docker-compose run oae-hilary 'npm install --prefix ./node_modules/oae-rest -s'
# install dependencies for 3akai-ux
- docker-compose run oae-hilary 'npm install --prefix ./3akai-ux -s '
# install dependencies for Hilary
- docker-compose run oae-hilary 'npm install -s'

before_script:
# - docker-compose up -d
# - sleep 10
# - docker-compose stop oae-hilary
# - sleep 60

script:
# - docker-compose run oae-hilary 'grunt test-module:oae-activity'
# - docker-compose run oae-hilary 'grunt test-module:oae-authentication'
# - docker-compose run oae-hilary 'grunt test-module:oae-authz'
# - docker-compose run oae-hilary 'grunt test-module:oae-config'
# - docker-compose run oae-hilary 'grunt test-module:oae-content'
# - docker-compose run oae-hilary 'grunt test-module:oae-context'
# - docker-compose run oae-hilary 'grunt test-module:oae-discussions'
# - docker-compose run oae-hilary 'grunt test-module:oae-doc'
# - docker-compose run oae-hilary 'grunt test-module:oae-emitter'
# - docker-compose run oae-hilary 'grunt test-module:oae-email'
# - docker-compose run oae-hilary 'grunt test-module:oae-following'
# - docker-compose run oae-hilary 'grunt test-module:oae-folders'
# - docker-compose run oae-hilary 'grunt test-module:oae-google-analytics'
# - docker-compose run oae-hilary 'grunt test-module:oae-library'
# - docker-compose run oae-hilary 'grunt test-module:oae-logger'
# - docker-compose run oae-hilary 'grunt test-module:oae-messagebox'
# - docker-compose run oae-hilary 'grunt test-module:oae-mediacore'
# - docker-compose run oae-hilary 'grunt test-module:oae-mixpanel'
# - docker-compose run oae-hilary 'grunt test-module:oae-preview-processor'
# - docker-compose run oae-hilary 'grunt test-module:oae-principals'
# - docker-compose run oae-hilary 'grunt test-module:oae-resource'
# - docker-compose run oae-hilary 'grunt test-module:oae-release-tools'
# - docker-compose run oae-hilary 'grunt test-module:oae-rest'
# - docker-compose run oae-hilary 'grunt test-module:oae-search'
# - docker-compose run oae-hilary 'grunt test-module:oae-telemetry'
# - docker-compose run oae-hilary 'grunt test-module:oae-tincanapi'
# - docker-compose run oae-hilary 'grunt test-module:oae-tests'
# - docker-compose run oae-hilary 'grunt test-module:oae-tenants'
# - docker-compose run oae-hilary 'grunt test-module:oae-util'
# - docker-compose run oae-hilary 'grunt test-module:oae-ui'
# - docker-compose run oae-hilary 'grunt test-module:oae-uservoice'
- docker-compose run oae-hilary 'grunt test-module:oae-version'

# after_success:

# after_failure:

# after_script:
